### ISSUE TITLE
Tests are failing due sqlite3 Integrity error

### ISSUE THREAD

**Issue by araujofrancisco** [ashutoshkrris/Flask-User-Authentication#2]
test_validate_invalid_email_format (test_forms.TestLoginForm) ... ERROR
test_validate_success_login_form (test_forms.TestLoginForm) ... ERROR
test_validate_email_already_registered (test_forms.TestRegisterForm) ... ERROR
test_validate_invalid_password_format (test_forms.TestRegisterForm) ... ERROR
test_validate_success_register_form (test_forms.TestRegisterForm) ... ERROR
test_check_password (test_models.TestUser) ... ERROR
test_created_on_defaults_to_datetime (test_models.TestUser) ... ERROR
test_get_by_id (test_models.TestUser) ... ERROR
test_user_registration (test_models.TestUser) ... ERROR
test_validate_invalid_password (test_models.TestUser) ... ERROR
test_correct_login (test_routes.TestLoggingInOut) ... ERROR
test_logout_behaves_correctly (test_routes.TestLoggingInOut) ... ERROR
test_logout_route_requires_login (test_routes.TestPublic) ... ERROR
test_main_route_requires_login (test_routes.TestPublic) ... ERROR

======================================================================
ERROR: test_validate_invalid_email_format (test_forms.TestLoginForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/franciscoa/.venv/flash-basic-auth/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/franciscoa/.venv/flash-basic-auth/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: users.email

**Comment by ashutoshkrris** [comment]
Hi @araujofrancisco 
If possible, could you push your code to a GitHub repository and share the link to it here, so that I can view your code?

**Comment by araujofrancisco** [comment]
> Hi @araujofrancisco If possible, could you push your code to a GitHub repository and share the link to it here, so that I can view your code?

I did a git clone on the code here, only changed the folder for the repository. I did applied upgrades to python libraries not sure if that can be causing issues.

**Comment by araujofrancisco** [comment]
I did clone repository again and got it fixed, so the issue was caused by the upgraded libraries, I used pip-upgrader for that just in case you want to try.
